### PR TITLE
Compiler: demote compile time to info instead of error

### PR DESCRIPTION
**Pull request by ekiwi-sifive**
fixes https://github.com/freechipsproject/firrtl/issues/1680

### CODE REVIEW

**Comment by seldridge** [comment]
How far back should we backport this? 

This can be backported to 1.2.x, but the patch is totally different:

```diff
diff --git a/src/main/scala/firrtl/Compiler.scala b/src/main/scala/firrtl/Compiler.scala
index 4f17b4f0..744d9f92 100644
--- a/src/main/scala/firrtl/Compiler.scala
+++ b/src/main/scala/firrtl/Compiler.scala
@@ -487,7 +487,7 @@ trait Compiler extends LazyLogging {
       }
     }
 
-    logger.error(f"Total FIRRTL Compile Time: $timeMillis%.1f ms")
+    logger.info(f"Total FIRRTL Compile Time: $timeMillis%.1f ms")
 
     finalState
   }
```

**Comment by ekiwi-sifive** [comment]
> How far back should we backport this?

Should this be backported at all? Seems like it would alter the user experience.

**Comment by seldridge** [comment]
Re: backporting: I think the policy at this point has been to greedily backport. I.e., backport a PR as far back as it will reasonably go without an API breakage.

Or, inductively: if this PR provides a better user experience in 1.4, then it's a better 1.3.x experience, then it's a better 1.2.x experience...

Thoughts @jackkoenig.

**Comment by jackkoenig** [comment]
I wouldn't backport this, at least not to `1.2.x`. I think the argument can be made for `1.3.x` since it's kind of the "current stable release branch". In general I see these kinds of things as changing on major boundaries but I don't feel that strongly about it.

**Pull request merged**
