### PR TITLE
Add asynchronous reset support

### PR DESCRIPTION
**Pull request by dalance**
This PR is an implementation of #219.

### CODE REVIEW

**Comment by dalance** [comment]
Hi @azidar , Thanks.
I agree that IR level solution is better than this PR.
I'll wait for the meeting result.

**Comment by aswaterman** [comment]
I think this is problematic for a few reasons:

- It's not correct in general to simply replace synchronous resets with asynchronous resets.  What if the reset is computed from combinational logic, so can glitch?

- It's hard-coded to a signal named reset.  This is just a convention, not a requirement.  I might have a signal called "reset" whose purpose is not that of a reset.

- The ifdef approach is going to cause a backwards-compatibility issue once async reset is represented properly in the IR.  At that point, the polarity will also be part of the IR, not something specified by a macro.

**Comment by schoeberl** [comment]
Using synchronous or asynchronous reset is a property of the receiving flip-flop (a technology question). Sometimes asynchronous (e.g., in older FPGAs), sometimes synchronous may be cheaper.

Independent from which reset input type one uses, the register signal has to be synchronous to the clock. Reset (also synchronous version) shall not violate setup and hold time. If reset comes from a pin as a synchronous signal it has to go through an input synchronizer (two flip-flops).

That also means that a reset coming from a register (output) is fine for a synchronous and an asynchronous reset. If one wants to add logic to that signal (which is probably not good design style in my opinion) it is ok as long as it fits into one clock cycle. Same for both cases.

I agree that this is a useful short-time solution and would give it a try.

**Comment by schoeberl** [comment]
> On 7 Dec, 2018, at 14:43, Andrew Waterman <notifications@github.com> wrote:
> 
> I think this is problematic for a few reasons:
> 
> It's not correct in general to simply replace synchronous resets with asynchronous resets. What if the reset is computed from combinational logic, so can glitch?
> 
Yes, this is a gotcha. (Mistake in my former comment) Agree when you have logic in your reset path you should not switch to an asynchronous reset and stick to the synchronous reset. You should first remove the logic from the reset path ;-)

A synchronous reset is basically only logic in front of the flip-flop (mux with one input the reset value). As it is so common, FPGAs start to add this signal extra to the filp-flops to not wast LUTs.

Martin

**Comment by dalance** [comment]
I think the issue of reset logic and "reset" name can't be resolved by current IR because IR don't have the information about reset.
The issue of "ifdef" compatibility may be resolved by command-line option like below?

```
firrtl --reg-reset <sync|async_pos|async_neg>
```

But I can't find the way to pass an option to VerilogEmitter...

**Comment by azidar** [comment]
So the dev meeting was mixed in its feelings towards this - we are seeking additional feedback from @aswaterman and @schoeberl and anyone else interested in commenting.

**Comment by jackkoenig** [comment]
Superseded by https://github.com/freechipsproject/firrtl/pull/1011

**Pull request closed without merging**
