### PR TITLE
[ExpandWhens] Don't create nodes to hold Muxes with >0 void cases

### PR DESCRIPTION
**Pull request by albert-magyar**
Fixes https://github.com/freechipsproject/firrtl/issues/852

### CODE REVIEW

**Comment by jackkoenig** [comment]
The `WVoids` are checked in `CheckInitialization` so won't this break initialization checking?

**Comment by albert-magyar** [comment]
The `WVoids` are still there, they just appear in inline expressions instead of getting assigned to nodes that are now illegal.

**Comment by azidar** [comment]
Do you want to grab the test case from #1037 ? Your solution is definitely better than mine :)

**Comment by jackkoenig** [comment]
oh nice, this is great 🙂

**Comment by albert-magyar** [comment]
I generalized it to cover cases where `ValidIf`s with a `WVoid` defaults and `Mux`es with `WVoid` cases are mixed. I also added a deeper test case that covers this scenario.

**Comment by albert-magyar** [comment]
@azidar, I talked to Jack, and I ended up using `MemoizedHash` to memoize the expressions. This should provide a  similar performance benefit to hashing the LHS values, and it definitely makes the `WVoid` checks a lot easier to understand.

**Comment by azidar** [comment]
Will commenting rerun mergify?

**Comment by albert-magyar** [comment]
So I'm guessing no?

**Pull request merged**
