### PR TITLE
Use Mergify to automate backporting to 1.2.x

### PR DESCRIPTION
**Pull request by jackkoenig**
Now, any PR **merged** to master with Milestone `1.2.X` will have a backport PR automatically generated.

### Checklist

- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### Type of Improvement

Release automation improvement

### API Impact

No change

### Backend Code Generation Impact

No change

### Desired Merge Strategy

Squash

### CODE REVIEW

**Comment by jackkoenig** [comment]
I also added labeling to try to help organize backporting. The basic problems I'm trying to solve are
1. Backport bug fixes to stable (1.2.x)
2. Help @ucbjrl or whoever is doing releases *know* that things have been backported properly

These changes will have Mergify automatically back port PRs that have the Milestone `1.2.X`, it will then label the PR `Backported` and once it creates a new PR against branch `1.2.x` it will label it `Backport`. The idea here is that we can check the Milestone `1.2.X` to ensure everything has been properly backported and we can check that back ports have been properly merged.

This means cleaning up some old PRs, to illustrate what I'd like to see, I changed https://github.com/freechipsproject/firrtl/pull/1202 to Milestone `1.2.X`, labeled it `Backported` and then labeled the back port of that PR https://github.com/freechipsproject/firrtl/pull/1225 `Backport`.

What do people think?

**Comment by jackkoenig** [comment]
That comment was very repetitive, but hopefully it gets the idea across 😅

**Comment by albert-magyar** [comment]
That makes sense. And the mention in the new PR will pop up in the conversation of the original PR.

**Comment by jackkoenig** [comment]
> That makes sense. And the mention in the new PR will pop up in the conversation of the original PR.

Yeah exactly, they are linked, we just want some way of checking that we are actually back porting stuff. Checking that everything is labeled with either `Backport` or `Backported` in `1.2.X` seems like a reasonable way of doing this.

If we adopt this flow, we'll probably want to move stuff in Milestone `1.2.X` to `1.2.0` or elsewhere.

**Comment by jackkoenig** [comment]
The only negative is that issues also get the milestone, but they're marked with different icons so it's fairly easy to tell you can ignore them.

**Pull request merged**
