### PR TITLE
Fix SMT Memory Bug

### PR DESCRIPTION
**Pull request by ekiwi**
This fixes two bugs in the SMT backend:
- I forgot to scan assert/assume expressions to see if they use memory read ports
- there was a typo in the code that generates conditions to detect write/write conflicts

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- n/a Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

#### Type of Improvement
- bug fix

#### API Impact
- none

#### Backend Code Generation Impact

- fixes generated SMTLib/Btor2 representation

#### Desired Merge Strategy

- squash

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by ekiwi** [comment]
@jackkoenig do you know why the Chisel3 tests might be failing?

**Review by azidar — APPROVED** [review]

**Comment by jackkoenig** [comment]
> @jackkoenig do you know why the Chisel3 tests might be failing?

It's known flakiness (but unknown reason why), just restart the test

**Comment by ekiwi** [comment]
Seems like the Chisel test always exceeds its maximum length (+ it has all the broken pipe warnings).
Since the Chisel tests do not use the smt backend, I am not sure why this is the case for this PR.

I did restart the tests twice by force pushing to the PR branch.

**Comment by jackkoenig** [comment]
Travis is having issues and pulling resources away from their free open-source offering, that could be related. We probably need to switch to a different CI host anyway and perhaps that can at least workaround this issue. I'll poke around with Github Actions

**Comment by ekiwi** [comment]
@Mergifyio backport 1.4.x

**Comment by ekiwi** [comment]
@Mergifyio backport 1.4.x

**Pull request merged**
