### PR TITLE
EliminateTargetPaths: don't duplicate modules with only one instance

### PR DESCRIPTION
**Pull request by albertchen-sifive**
### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

This PR prevents `EliminateTargetPaths` from renaming modules with only a single instance. This is done by adding a prepocessing step that shortens target paths if they contain inst/ofMod pairs that are lone instances.

example:
```
circuit Foo:
  module Baz:
    skip
  module Bar:
    inst baz of Baz
    inst bazzz of Baz
  module Foo:
    inst bar of Bar
```
resolving `~Foo|Foo/bar:Bar/baz/Baz` and `~Foo|Foo/bar:Bar/baz/Bazzz` will create two `RenameMap`s. The first one renames
```
~Foo|Foo/bar:Bar/baz:Baz -> ~Foo|Bar/baz:Baz
~Foo|Foo/bar:Bar/bazzz:Baz -> ~Foo|Bar/bazzz:Baz
```
Then the usual duplication happens on `~Foo|Bar/baz:Baz` and `~Foo|Bar/bazzz:Baz`, which will only try to duplicate `Baz`. Finally, the two `RenameMap`s are chained together.

#### Type of Improvement

bug fix: this [unit test](https://github.com/freechipsproject/firrtl/blob/master/src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala#L401-L418) for `EliminateTargetPaths` does not actually check anything. Running it shows that it the property it should be testing does not actually hold. `EliminateTargetPaths` turns this:
```
circuit Foo:
  module Baz:
    skip
  module Bar:
    inst baz of Baz
    skip
  module Foo:
    inst bar of Bar
```

into this:
```
circuit Foo :
  module Baz___Foo_bar_baz :
    skip
  module Bar___Foo_bar :
    inst baz of Baz___Foo_bar_baz
    skip
  module Foo :
    inst bar of Bar___Foo_bar
```

#### API Impact

Should not affect the current API, aside from changing module names.

#### Backend Code Generation Impact

It should prevent modules from being renamed unnecessarily to long module path names.

#### Desired Merge Strategy

Squash

#### Release Notes

don't duplicate lone instance modules in EliminateTargetPaths

### Reviewer Checklist (only modified by reviewer)
- [x] Did you add the appropriate labels?
- [x] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [x] Did you review?
- [x] Did you check whether all relevant Contributor checkboxes have been checked?
- [x] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by mwachs5** [comment]
What does the fixed test do in this case now?

**Comment by albertchen-sifive** [comment]
> What does the fixed test do in this case now?

it checks that the circuit remains unchanged https://github.com/albertchen-sifive/firrtl/blob/fix-EliminateTargetPaths-lone-instances/src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala#L426 since all modules have only a single instance

**Comment by seldridge** [comment]
That's a nice test I added... :woman_shrugging: 

What's the behavior with: https://github.com/freechipsproject/firrtl/pull/1442 ?

**Comment by jackkoenig** [comment]
> resolving ~Foo|Foo/bar:Bar/baz/Baz and ~Foo|Foo/bar:Bar/baz/Bazzz will create two RenameMaps.

Does this mean that you get 1 RenameMap per instance? If I resolve all of the following: 
```
~Foo|Foo/a1:A
~Foo|Foo/a2:A
~Foo|Foo/b1:B
~Foo|Foo/b2:B
```
How many RenameMaps do I get? 2 or 4?

**Comment by albertchen-sifive** [comment]
> How many RenameMaps do I get? 2 or 4?

sorry, wording is a bit weird. it will be at most 2 RenameMaps. first RenameMap has all the renames for single instance paths, second one is the duplication RenameMap. if there are no renames in the first pass, then just the duplication map will be used.

> What's the behavior with: #1442 ?

haven't read all of that PR, and I have to admit I still don't fully understand the AST module stuff. but I think this should still work fine with that PR? not sure

**Comment by jackkoenig** [comment]
> sorry, wording is a bit weird. it will be at most 2 RenameMaps. first RenameMap has all the renames for single instance paths, second one is the duplication RenameMap. if there are no renames in the first pass, then just the duplication map will be used.

Got it, great.

This looks like a bug fix, is that correct? Is the only side effect of this PR that modules with only a single instance do not get duplicated in `EliminateTargetPaths`?

**Comment by albertchen-sifive** [comment]
> This looks like a bug fix, is that correct? Is the only side effect of this PR that modules with only a single instance do not get duplicated in `EliminateTargetPaths`?

yes

**Pull request merged**
