### PR TITLE
Emitter: clean up with scalastyle and IntelliJ suggestions

### PR DESCRIPTION
**Pull request by ekiwi-sifive**
### Contributor Checklist

- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement
- code cleanup

#### API Impact
- makes some methods of the Emitter private

#### Backend Code Generation Impact
- any change in code generation is a bug

#### Desired Merge Strategy
- squash

#### Release Notes

n/a

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by ekiwi-sifive** [comment]
Let's see if the tests will pass....

**Comment by seldridge** [comment]
I'm in favor of doing this, but by reviving the scalafmt PR: https://github.com/freechipsproject/firrtl/pull/1234. This should probably be done at the 1.4 boundary.

**Comment by ekiwi-sifive** [comment]
> I'm in favor of doing this, but by reviving the scalafmt PR: #1234. This should probably be done at the 1.4 boundary.

You can always run `scalafmt` on top of this PR. However, getting a complete reformatting merged is going to be controversial and will not happen by the end of this week. Meanwhile every time I open `Emitter.scala` in IntelliJ everything is an exploding mix of colors and it is really hard to see the code for the many warnings.

**Comment by ekiwi-sifive** [comment]
This passes all the tests and I would appreciate if we could merge it in order to get rid of the worst offender when it comes to code style.

I am also in favor of applying `scalafmt` right before we release `firrtl 1.4`, however, that will take some time and we will need to discuss it at the developers' meeting.

**Comment by jackkoenig** [comment]
This issue is that big changes like this make (basically) every single backport that touches the changed file conflict and require manual fixups. So the desire to do it closer to release of the next version is that backports in the meantime still apply.

**Comment by ekiwi-sifive** [comment]
> This issue is that big changes like this make (basically) every single backport that touches the changed file conflict and require manual fixups

OK. So how about I make a smaller PR that just adds the `scalastyle:off` ignore comments. That shouldn't be problematic for backports and solves about 70% of my immediate problems.

**Comment by ekiwi-sifive** [comment]
Minimal PR: https://github.com/freechipsproject/firrtl/pull/1711

**Pull request closed without merging**
