### PR TITLE
spec: mixed-input arguments for prim ops are no longer allowed

### PR DESCRIPTION
**Pull request by ekiwi**
This updates the spec to refelect the changes made in #587.
It also fixes issue #968.

### CODE REVIEW

**Comment by ekiwi** [comment]
Let me know if I should also check in the rebuilt pdf.

**Comment by edwardcwang** [comment]
I wonder if we should just remove the cached copy of the spec to prevent it from becoming stale/out-of-date if we don't plan to update it regularly.

**Comment by ekiwi** [comment]
> I wonder if we should just remove the cached copy of the spec to prevent it from becoming stale/out-of-date if we don't plan to update it regularly.

That sounds like a good idea. Maybe generate the pdf in the CI.

**Comment by aswaterman** [comment]
That would be better, for a number of reasons.  You can use the RISC-V spec as an example of how to do it: https://github.com/riscv/riscv-isa-manual/blob/master/.travis.yml (note you need to generate a github access token with write perms to this repo, then go to the Travis setup for this repo, and define a variable named github_access_token with the value of your token).

**Pull request merged**
