### PR TITLE
Support Java API doc Scaladoc/Unidoc References

### PR DESCRIPTION
**Pull request by seldridge**
This enables automatic Scaladoc linking to Java API docs using the same strategy that Scala upstream uses.

Linking to Scala API documentation already works.

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### Type of Improvement

- documentation

### API Impact

None.

### Backend Code Generation Impact

None.

### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by seldridge** [comment]
I have no earthly idea why this isn't building on Travis... :woman_shrugging: This works locally with a clean clone and a nuked `~/.ivy2`.

**Comment by ucbjrl** [comment]
It looks like the plugin has been compiled for Java 8 and won't work with Java 11 or 13.

**Comment by seldridge** [comment]
Ugh, thanks Jim. Scala does something different for linking to Java API docs. I can at least add that.

**Comment by ucbjrl** [comment]
The incompatibility doesn't appear to be fundamental in nature. If you generate a full log, you get:
```
[error] scala.MatchError: 11 (of class java.lang.String)
[error] 	at com.thoughtworks.sbtApiMappings.BootstrapApiMappings$.$anonfun$globalSettings$1(BootstrapApiMappings.scala:28)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:823)
```
and the code at that location is:
```
  private[sbtApiMappings] def defaultBootstrapJavadocUrl = {
    val javaVersion = sys.props("java.specification.version") match {
->      case VersionNumber(Seq(1, javaVersion, _*), _, _) => javaVersion // 1.6-1.8
        case VersionNumber(Seq(javaVersion, _*),    _, _) => javaVersion // 9+
        case _ =>                                            8
    }
    if (javaVersion >= 11) {
      url(s"https://docs.oracle.com/en/java/javase/${javaVersion}/docs/api/index.html")
    } else {
      url(s"https://docs.oracle.com/javase/${javaVersion}/docs/api/index.html")
    }
  }
```
`java.specification.version` for post Java 8 differs between Oracle Java and OpenJDK. See https://stackoverflow.com/questions/5103121/how-to-find-the-jvm-version-from-a-program
We need more standards.

**Comment by seldridge** [comment]
I switched this to not use the sbt-api-mappings plugin to avoid the issue that @ucbjrl found (also that plugin is sparsely updated making me nervous). Instead, this uses the same strategy that Scala uses to link against Java API documentation. The small example included works for unidoc.

**Pull request merged**
