### PR TITLE
Add support for mill

### PR DESCRIPTION
**Pull request by ucbjrl**
This is patterned after @grebe's work on [dsptools](https://github.com/ucb-bar/dsptools/tree/mill). It's not completely baked - the current release of mill is missing some features:
 - doesn't handle symbolic links
 - doesn't restrict source files for Java/ScalaDoc.

There is a fix in the master branch for the former, and I'm submitted a PR for the latter.
In the meantime, I've set `make` to fetch the `mill` executable from my fork of the repo.

This shouldn't interfere with `sbt` usage - I've added a `Module` definition that reflects our `sbt` layout.

The new `make` targets are:
- `mill.build` - compile and package the `firrtl.jar` for the default (first) crossVersion,
- `mill.build.all` - compile and package `firrtl.jar` for all crossVersions,
- `mill.test` - compile and test the default (first) crossVersion,
- `mill.test.all` - compile and test all crossVersions,
- `mill.publishLocal` - compile and publishLocal the `firrtl.jar` for the default (first) crossVersion,
- `mill.publishLocal.all` - compile and publishLocal the `firrtl.jar` all crossVersions,

These targets include dependencies on `mill` and `antlr-4.7.1-complete.jar` and they will be downloaded and installed in the `$HOME/bin` and `$HOME/lib` directories respectively (once). **If `$HOME/bin` isn't in your `PATH`, you'll need to add it.**

Check out [mill](https://github.com/lihaoyi/mill) (or my [fork](https://github.com/ucbjrl/mill)) for documentation and examples.

### CODE REVIEW

**Comment by jackkoenig** [comment]
Thank you for doing this!

I'm in the process of fixing the Travis regressions, once https://github.com/freechipsproject/firrtl/pull/812 is merged I'll merge master and I'll stop killing your builds :)

I think we should probably include this in the Travis regressions as well?

**Comment by chick** [comment]
@ucbjrl is this still in play?

**Comment by ucbjrl** [comment]
Very much so. I'm going to bring dsptools back into the fold (at which point all of the BIG6 will support building with mill). @jackkoenig  is working on rocketchip support and the ability to switch between source and library dependencies.

**Comment by chick** [comment]
@ucbjrl Has this been superseded by other mill work? If not can conflicts be resolved and I will review.

**Comment by chick** [comment]
@ucbjrl any update on the status of this or the fixing of conflicts

**Comment by ucbjrl** [comment]
I've updated this branch. We were waiting on two items:
- @jackkoenig's work with rocket-chip,
- switching to the official mill release

before merging this.

**Comment by jackkoenig** [comment]
This branch currently has a bunch of commits that are already on master, it seems that the history has diverged in a serious way. Given the CLA comment above, we should probably rebase this branch to remove those unnecessary commits.

**Comment by edwardcwang** [comment]
I've been using the `prototype-mill` branch and have some updates there as well. Maybe we can just combine all the changes into one big squashed commit and open it as a new PR to avoid this history divergence?

**Comment by edwardcwang** [comment]
Closing in favor of #1083 given the serious divergence in this branch.

**Pull request closed without merging**
