### PR TITLE
Support infoMode for Strings

### PR DESCRIPTION
**Pull request by edwardcwang**
It seemed like an API hole that I couldn't use infoMode with a string but had to manually create an iterator first.

### CODE REVIEW

**Comment by edwardcwang** [comment]
Okay. I'd imagine the `parse(string)` case is slightly more common, so kept the default there.

**Comment by edwardcwang** [comment]
Arrrgh. Will take another stab at it later.

**Comment by azidar** [comment]
@ucbjrl will look into

**Comment by ucbjrl** [comment]
@edwardcwang could you sign off on this if you feel it satisfies your use case?

**Comment by edwardcwang** [comment]
LGTM!

**Pull request merged**
