### PR TITLE
Omnibus Dependency API Updates

### PR DESCRIPTION
**Pull request by seldridge**
This includes changes to the `dependency-api-2` branch without including a port of FIRRTL transforms to use the Dependency API. Roughly this includes (by commit, roughly):

- @albert-magyar's singleton transform work
- an optional prerequisites method
- a textual pretty-printer for a dependency manager
- additional tests
- a `final` modifier inside the `PreservesAll` trait

This breaks Chisel, but there's an outstanding PR on Chisel (https://github.com/freechipsproject/chisel3/pull/1270) that should fix it. I'm testing intermediate commits and that Chisel3 works with this now.

I'm trying to get this in independent of the `dependency-api-2` branch because it appears that the Rocket Chip Stage/Phase refactor (https://github.com/chipsalliance/rocket-chip/pull/2274) will require a `RunPhaseAnnotation`. This is needed, but I'd rather not do this independent of the changes to the Dependency API that this introduces. Ping @debs-sifive.

### Checklist

- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### Type of Improvement

- new feature/API

### API Impact

Breaks anything using the current Dependency API.

### Backend Code Generation Impact

None.

### Desired Merge Strategy

- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

### CODE REVIEW

**Comment by seldridge** [comment]
This is fine to review, but I'm adding the `DO NOT MERGE` tag as the companion Chisel PR needs to be updated.

**Comment by seldridge** [comment]
Bumping for a review.

This will break all of the @debs-sifive work in https://github.com/chipsalliance/rocket-chip/pull/2274 and I was hoping to get this in before Rocket Chip jumps to Stage/Phase.

**Comment by debs-sifive** [comment]
No worries, I will wait for this PR!

**Comment by seldridge** [comment]
I've run intermediate commits and tested that https://github.com/freechipsproject/chisel3/pull/1270 passes on both 2.11 and 2.12 when using this branch published locally. Going to go go ahead and merge after talking with @azidar out of band.

**Comment by albert-magyar** [comment]
Yay! So close to being 1 year from opening #1015, great job keeping track of everything.

**Pull request merged**
