### PR TITLE
Use scalafix to remove unused import and deprecated procedure syntax

### PR DESCRIPTION
**Pull request by colin4124**
I add scalafix and then run 

```shell
sbt "firrtl/scalafix ProcedureSyntax"
```
and
```shell
sbt "firrtl/scalafix RemoveUnused"
```

### CODE REVIEW

**Comment by azidar** [comment]
Great!!! Sorry for taking a while to look at this. I realize its unfortunately after we've merged another PR, would you mind updating it to master? Also, could you include a note in the README for how to run it? Thanks!

**Comment by colin4124** [comment]
@azidar I have done as your advice

**Comment by colin4124** [comment]
@azidar Would you have some time review this PR, is there any problem?

**Comment by colin4124** [comment]
There is CI error, missing verilator:

```
$ verilator --version
The program 'verilator' is currently not installed. To run 'verilator' please ask your administrator to install the package 'verilator'
The command "verilator --version" exited with 127.
```

**Comment by ucbjrl** [comment]
The failure appears to be due to Travis cacheing issues. I've explicitly cleared the cache (#1099) and restarted the Travis checks for this PR.

**Comment by azidar** [comment]
Thanks! Looks good, merging now

**Pull request merged**
