### PR TITLE
Make InstanceGraph have defined iteration order

### PR DESCRIPTION
**Pull request by jackkoenig**
DiGraph is deterministic but the construction of them via InstanceGraph is not. This PR makes it so.

I'm not a fan of explicitly returning mutable data structures, but as we all know, Scala kind of bites us on this by making the only immutable Map with defined iteration order very slow (ListMap).

`SeqMap` may exist in Scala 2.13, and may even have a reasonable implementation with `VectorMap`: https://github.com/scala/scala/pull/6854. But as long as we're supporting Scala 2.12 we'll be stuck with this weird issue. We could copy the current implementation of VectorMap/LinkedMap (it's BSD licensed) https://github.com/mdedetrich/linked-map and use it within the compiler rather than returning LinkedHashMaps. I don't know, what do y'all think?

### CODE REVIEW

**Comment by albert-magyar** [comment]
`grep -r "[^d]HashMap" ./src`

**Comment by jackkoenig** [comment]
Terrifying. @albert-magyar What do you think about including an implementation of VectorMap and then we could use it all over in lieu of HashMap?

**Comment by albert-magyar** [comment]
We could definitely do something. The tricky thing is that we have 4 cases:

1. Mutated, iteration order used to generate hardware
2. Mutated, iteration order not used to generate hardware
3. Constant, iteration order used to generate hardware
4. Constant, iteration order not used to generate hardware

And then people use things in slightly different ways and the categories bleed into each other :(

**Comment by mdedetrich** [comment]
@jackkoenig Just chiming in here

The intention of https://github.com/mdedetrich/linked-map is its going to be a polyfill for SeqMap/Vector map for Scala 2.12 and lower, so that you still have complete source code compatibility across Scala versions minor one proviso (which is that I can't make `LinkMap` extend `SeqMap` since its an external library, maybe there is some hacky way to do this)

I haven't finalized worked on https://github.com/mdedetrich/linked-map because I am waiting for the `SeqMap` design to be finalised (I for example have to rename `LinkedMap` to `SeqMap`)

**Comment by jackkoenig** [comment]
@mdedetrich Thank you for your consideration!

That all makes sense! Is your plan with https://github.com/mdedetrich/linked-map to publish it or is it something we should consider including it as a submodule? I would love to use it here as a polyfill!

Thank you for your work on this!

**Comment by mdedetrich** [comment]
@jackkoenig I will publish it, but only when the design is finalized. Its supposed to be ultra stable, so I will only make a release when everything is good and the performance of the implementation is adequate

**Pull request merged**
