### PR TITLE
Update MiMa check to include all 1.2.x releases

### PR DESCRIPTION
**Pull request by jackkoenig**
### Contributor Checklist

- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### API Impact

Enforce binary compatibility against all previously published versions on the release branch

### Backend Code Generation Impact

None

### Desired Merge Strategy

Don't care

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by jackkoenig** [comment]
How did I test this? I deleted all firrtl jars from my cache and ensured that `mimaReportBinaryIssues` downloaded each version:
```
sbt:firrtl> mimaReportBinaryIssues
[info] downloading https://repo1.maven.org/maven2/edu/berkeley/cs/firrtl_2.12/1.2.4/firrtl_2.12-1.2.4.jar ...
[info]  [SUCCESSFUL ] edu.berkeley.cs#firrtl_2.12;1.2.4!firrtl_2.12.jar (327ms)
[info] downloading https://repo1.maven.org/maven2/edu/berkeley/cs/firrtl_2.12/1.2.3/firrtl_2.12-1.2.3.jar ...
[info]  [SUCCESSFUL ] edu.berkeley.cs#firrtl_2.12;1.2.3!firrtl_2.12.jar (331ms)
[info] downloading https://repo1.maven.org/maven2/edu/berkeley/cs/firrtl_2.12/1.2.0/firrtl_2.12-1.2.0.jar ...
[info]  [SUCCESSFUL ] edu.berkeley.cs#firrtl_2.12;1.2.0!firrtl_2.12.jar (585ms)
[info] downloading https://repo1.maven.org/maven2/edu/berkeley/cs/firrtl_2.12/1.2.1/firrtl_2.12-1.2.1.jar ...
[info]  [SUCCESSFUL ] edu.berkeley.cs#firrtl_2.12;1.2.1!firrtl_2.12.jar (201ms)
[info] downloading https://repo1.maven.org/maven2/edu/berkeley/cs/firrtl_2.12/1.2.2/firrtl_2.12-1.2.2.jar ...
[info]  [SUCCESSFUL ] edu.berkeley.cs#firrtl_2.12;1.2.2!firrtl_2.12.jar (605ms)
[success] Total time: 6 s, completed Mar 11, 2020 12:25:46 PM
```

**Comment by jackkoenig** [comment]
Weird that tests are failing because it works for me locally...

**Comment by jackkoenig** [comment]
@seldridge I changed this to require binary compatibility with `1.2.+`, the idea being that it will always use the newest published version which means we should be inductively binary compatible all the way back to `1.2.0`, except for the fact that we haven't tested those. So I'm going to test that up to `1.2.4` manually, and then it should be true going forward.

**Comment by seldridge** [comment]
I'm good with the induction.

**Comment by ucbjrl** [comment]
What's the benefit over simply ensuring compatibility with 1.2.0?

**Comment by jackkoenig** [comment]
> What's the benefit over simply ensuring compatibility with 1.2.0?

If we add something in `1.2.1` then accidentally remove it, we wouldn't notice and then `1.2.2` could be binary incompatible with `1.2.1`. Unless you also enforce _forwards binary compatibility_ (which the Scala collections do), you need to check against each prior version.

**Comment by jackkoenig** [comment]
@seldridge @ucbjrl @albert-magyar I updated this to check for binary compatibility against `1.2.4` and I manually ran the check against `1.2.0`-`1.2.4` and confirmed that we are good so far 🙂

**Pull request merged**
