### PR TITLE
allowing overrides to $random

### PR DESCRIPTION
**Pull request by debs-sifive**
**Purpose:** Provides macros for overriding default `$random` behavior.
- After some discussion, putting `$urandom` directly into FIRRTL seems ill fitting, since `$urandom` is SystemVerilog specific.

**Files changed:** `src/main/scala/firrtl/Emitter.scala`

@jackkoenig 

## New macros

**`` `RANDOM``:** Can be overwritten, for example with `$urandom`.

**`` `INIT_RANDOM``:** Will be called on the `initial` block of every module before random function calls. Can be specified to run code such as `$srandom` calls.

### CODE REVIEW

**Comment by jackkoenig** [comment]
At long last, a fix for https://github.com/freechipsproject/firrtl/issues/598!

**Comment by edwardcwang** [comment]
Do we still care about the ability of the user to specify a custom random function?

**Comment by jackkoenig** [comment]
Yes, `$random` is awful. We had been using a sed script to replace `$random` with `$urandom` but it turns out that we really need to seed the random calls so that they're not identical for different instances of the same module. I suspect other people have done similarly hacky things so this provides a reasonable way to provide better randomization

**Comment by edwardcwang** [comment]
Yes, in addition to switching to `$urandom`, what about the ability for users to put in custom random functions (apart from `$random` / `$urandom`)?

**Comment by jackkoenig** [comment]
Yeah probably, perhaps instead of
```scala
        emit(Seq("`else"))
        emit(Seq("  `define RANDOM $urandom"))
```
It could be like
```scala
        emit(Seq("`else"))
        emit(Seq("  `ifndef RANDOM")
        emit(Seq("    `define RANDOM $urandom"))
        emit(Seq("   `endif"))
```
You might also then want to make the seeding be setable with ifdefs as well.

**Pull request merged**
