### PR TITLE
Fix copy-paste error in DiGraph.linearize documentation

### PR DESCRIPTION
**Pull request by sahandKashani**
### Checklist

- [y] Did you specify the type of improvement?
- [y] Did you state the API impact?
- [y] Did you specify the code generation impact?
- [y] Did you request a desired merge strategy?

### Type of Improvement

   - documentation                      

### API Impact

No changes.

### Backend Code Generation Impact

No changes.

### Desired Merge Strategy

   - Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

### CODE REVIEW

**Comment by albert-magyar** [comment]
@sahandKashani, I can merge this PR if you rebase, if that's what you'd like to do.

**Comment by sahandKashani** [comment]
Hi Albert. Yes, a rebase merge would be great. Thanks!

**Comment by albert-magyar** [comment]
@sahandKashani I was able to resolve the conflicts local, but I can't push fixes to your remote branch without access, so would you be able to update this?

**Comment by sahandKashani** [comment]
Sorry, it's the first time I'm submitting a PR to a repo other than one I own. Just to be sure I understand correctly, you'd need write access to my epfl-vlsc/firrtl repo to push your rebase changes, is that correct?

**Comment by albert-magyar** [comment]
No problem! We are always very grateful to get outside contributions.

> Just to be sure I understand correctly, you'd need write access to my epfl-vlsc/firrtl repo to push your rebase changes, is that correct?

Yes

**Comment by sahandKashani** [comment]
Great! Thanks.

You should have write access now.

**Comment by albert-magyar** [comment]
Great! I updated it and marked it for merging.

**Comment by sahandKashani** [comment]
Awesome. Thanks!

**Pull request merged**
