### PR TITLE
Fixed Mill SourcePath

### PR DESCRIPTION
**Pull request by colin4124**
its source directory is in the top level directory, not `firrtl/src/main/scala` .

### CODE REVIEW

**Comment by edwardcwang** [comment]
Just to double check, how are you currently using this as a mill submodule?

**Comment by colin4124** [comment]
@edwardcwang Sorry, I don't understand the "as a mill submodule" what it means. I use this firrtl repo as what it used to be. In other words, I use `mill` in this way, I clone firrtl repo and run 

```shell
mill firrtl.compile
```

I don't have to change any directory structure. I copy this code from chisel3's build.sc https://github.com/freechipsproject/chisel3/blob/master/build.sc#L143

**Comment by edwardcwang** [comment]
I have a project using mill that has firrtl as a submodule, and importing it in mill as a "foreign module" (mill terminology): https://github.com/lihaoyi/mill/blob/master/docs/pages/5%20-%20Modules.md#foreign-modules

**Comment by colin4124** [comment]
@edwardcwang I found the error: **Error: Invalid or corrupt jarfile  ...antlr-4.7.1-complete.jar**

Here are my project hierarchic：

```
foo/
    build.sc
    firrtl/
    bar/
        build.sc
```

**foo/build.sc**
```scala
import mill._, scalalib._

import $file.firrtl.build

object foo extends ScalaModule{
  def compile = T{
    firrtl.build.firrtl.compile()
  }
}
```

**foo/bar/build.sc**
```scala
import mill._, scalalib._

import $file.^.firrtl.build

object bar extends ScalaModule{

  def compile = T{
    ^.firrtl.build.firrtl.compile()
  }
}
```

Because of **pwd** in `val ANTLR4_JAR = (pwd / s"antlr-${antlr4Version}-complete.jar").toString`:

-  if I run `mill foo.compile` in `foo` directory,  `ANTLR4_JAR` would be `foo/antlr-4.7.1-complete.jar`; 
- if I run `mill bar.compile` in `bar` directory, `ANTLR4_JAR` would be `foo/bar/antlr-4.7.1-complete.jar`; 
- If I run `mill firrtl.compile` in `firrtl` directory, `ANTLR4_JAR` would be `foo/firrtl/antlr-4.7.1-complete.jar`.

The `ANTLR4_JAR` should be `foo/firrtl/antlr-4.7.1-complete.jar` whatever I run the compile command in any directory.

**Comment by edwardcwang** [comment]
Great! I will try this within the next few days. Thanks Colin!

**Comment by azidar** [comment]
Any update on this, @edwardcwang ?

**Comment by edwardcwang** [comment]
Sorry for falling behind on this. I will aim to try it out either this weekend or hopefully early next week...

**Comment by sequencer** [comment]
This works fine, just tested with `mill mill.scalalib.GenIdea/idea` and `mill firrtl.compile`.

**Comment by edwardcwang** [comment]
The issue is that we also want it to work in "subproject configuration"...

**Comment by azidar** [comment]
So sounds like this still requires work, @edwardcwang ? perhaps you can clarify?

**Comment by edwardcwang** [comment]
I think #1368 may obsolete this. Will test with #1368

**Comment by colin4124** [comment]
Ok, so I close it?

**Pull request closed without merging**
