### PR TITLE
Mill Support

### PR DESCRIPTION
**Pull request by sequencer**
### Checklist

- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### Type of Improvement
This PR gives mill support based on the newest mill API,
including cross compile and test.

#1083 gives a good example to this, but since it contains out-of-date APIs, it should be deprecated.

Here are some difference between #1083 and this PR:
1. antlr4 and protoc are generated based on `mill.Task` API to improve dependence and caching ability.
2. don't vendor commands, since mill has its own implementation. For example, firrtl could be run with `mill -i "firrtl[2.11.12].run"` or `mill -i "firrtl[2.12.10].run"`, and "jar", "publishLocal" is the same.
3. didn't vendor `BuildInfo` since it didn't used in firrtl.

### API Impact
None

### Backend Code Generation Impact
None

### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### CODE REVIEW

**Comment by edwardcwang** [comment]
Looks like a transient build failure on Travis' part.

**Comment by sequencer** [comment]
seems like the issue from travis: https://travis-ci.org/freechipsproject/firrtl/jobs/647153248#L240

**Comment by azidar** [comment]
Should we add a test to CI to make sure this gets built with all PRs?

**Comment by edwardcwang** [comment]
@azidar If you think that would be good we can add it to the travis yml

**Comment by sequencer** [comment]
Any update for this PR?

**Comment by edwardcwang** [comment]
> If you think that would be good we can add it to the travis yml

If this is still important we can do it in a subsequent PR

**Pull request merged**
