### PR TITLE
Cleanup Named Targets

### LINKED ISSUE #1304: Renaming ComponentName pointing at an Instance Doesn't Work
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [x] Did you specify relevant external information?

### What is the current behavior?

If you generate an annotation from a `ComponentName` pointing at an instance this will not be renamed properly if you populate a `RenameMap` with an `InstanceTarget` key. The reason for this is that `ComponentName` is converted to a `ReferenceTarget` and this is treated differently from an `InstanceTarget` from the perspective of renaming.

### What is the expected behavior?

You should be able to do renaming in this way. Users may be using legacy Chisel annotators that do not generate the correct type of target.

### Steps to Reproduce

The following simple test case fails.

```scala
val foo = CircuitTarget("Top").module("Top").instOf("foo", "Mod")
val bar = CircuitTarget("Top").module("Top").instOf("bar", "Mod")

val fooToo = ComponentName("foo", ModuleName("Top", CircuitName("Top"))).toTarget

val renames = RenameMap()
renames.record(foo, bar)

renames.get(fooToo) should be (Some(Seq(bar)))
```

### Your environment

- FIRRTL 2dc005d500ffcccef5def5938dc7ead7c68644b3 (master at the time of filing)

### External Information

None.

### PR DESCRIPTION
**Pull request by seldridge**
This adds a new transform, `CleanupNamedTargets`, that converts any `ReferenceTarget`s pointing at instances to `InstanceTarget`s. 

Fixes #1304.

### Checklist

- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### Type of Improvement

- bug fix

### API Impact

None.

### Backend Code Generation Impact

None.

### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### CODE REVIEW

**Comment by azidar** [comment]
I think this is ok, although I'd like @jackkoenig 's feedback if possible.

**Comment by azidar** [comment]
@jackkoenig Please review if possible. @seldridge please update to new dependency API.

**Comment by seldridge** [comment]
Updated to Dependency API. Ready for a @jackkoenig look. :eyes:

**Comment by seldridge** [comment]
@ekiwi-sifive: Thanks for bumping this. Rebased onto master with conflicts resolved.

**Pull request merged**
