### PR TITLE
Switch from sbt-protobuf to sbt-protoc + minor sbt cleanup

### PR DESCRIPTION
**Pull request by kammoh**
This solved to failing compile of master on my system (macOS, Java 12, sbt 1.3.0-RC2).  No matter what I did, `FirrtlProtos.java` was not being generated by `compile` or `protobufGenerate` tasks. 

`sbt-protoc` (https://github.com/thesamet/sbt-protoc) is being advertised as superseding `sbt-protobuf` and resolved this issue.

### CODE REVIEW

**Comment by azidar** [comment]
@ucbjrl can you review this?

**Comment by ucbjrl** [comment]
This looks good to me, but I'm getting some errors running on OpenJDK 11. I'll try to sort them out and report back. @jackkoenig do you have any concerns?

**Comment by ucbjrl** [comment]
This appears to tickle a JDK 11 bug which should be fixed in 11.0.4 (and JDK 12). It's not 100% reproducible but it seems to fail pretty consistently in our Jenkins environment. I don't think this should hold up this PR, but I leave it up to @jackkoenig to approve.

**Comment by kammoh** [comment]
I switched my local version of sbt (in `build.properties) to `1.3.0-RC2` and the `sbt-protobuf` plugin started working again for me! Has anyone else being experiencing this problem as well?

**Comment by ucbjrl** [comment]
This passes under Java 11, but seems to interact poorly with Antlr under Java 8, on OSX consistently producing:
```bash
sbt +clean +publishLocal +test
 ...
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Reapplying settings...
[info] Set current project to firrtl (in build file:.../firrtl/)
 ...
[info] 	published ivy to .../.ivy2/local/edu.berkeley.cs/firrtl_2.11/1.3-SNAPSHOT/ivys/ivy.xml
[success] Total time: 85 s (01:25), completed Dec 11, 2019 10:52:02 AM
[info] Setting Scala version to 2.12.10 on 1 projects.
[info] Reapplying settings...
[info] Set current project to firrtl (in build file:.../firrtl/)
 ...
[info] 	published ivy to .../.ivy2/local/edu.berkeley.cs/firrtl_2.12/1.3-SNAPSHOT/ivys/ivy.xml
[success] Total time: 83 s (01:23), completed Dec 11, 2019 10:53:26 AM
[info] Reapplying settings...
[info] Set current project to firrtl (in build file:.../firrtl/)
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Reapplying settings...
 ...
[info] Compiling protobuf
[info] Protoc target directory: ...firrtl/target/scala-2.11/src_managed/main
[info] Compiling 4 Java sources to .../firrtl/target/scala-2.11/classes ...
[warn] bootstrap class path not set in conjunction with -source 1.7
[error] An input/output error occurred.
[error] Consult the following stack trace for details.
[error] java.io.FileNotFoundException: ...firrtl/target/scala-2.11/src_managed/main/firrtl/antlr/FIRRTLBaseVisitor.java (No such file or directory)

```

**Comment by kammoh** [comment]
Since sbt-protobuf 0.6.5 is working fine under Java 11/13, I’m gonna close this for now. Please feel free to re-open/update if deemed necessary.

**Pull request closed without merging**
